### ISSUE TITLE
Поправить отображение дропбоксов на странице с товаром для маленьких экранов

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/Benefito#1]
Сейчас выглядит криво 
![image](https://cloud.githubusercontent.com/assets/8807333/6997944/ea02fd98-dbd8-11e4-87a3-8d690aa7bdbf.png)

**Comment by zakhnikita** [comment]
Поправил отображение
![2015-04-05 22 10 15](https://cloud.githubusercontent.com/assets/8578786/6998185/94177618-dbe0-11e4-8ed9-ddc1a7862edf.png)
