### ISSUE TITLE
надо решить с корзиной, что делать с корзиной боковой 

### ISSUE THREAD

**Issue by stler** [LeagueOfDevelopers/Benefito#12]

**Comment by Sovent** [comment]
Ну описание там явно не нужно. Указывать дополнительные атрибуты, вроде размера и пола, если есть, а если нет - просто название и цену.

**Comment by Sovent** [comment]
И сумму внизу, желательно бы

**Comment by zakhnikita** [comment]
Предлагаю её вовсе убрать
Либо оставить только название-цена

**Comment by Sovent** [comment]
Не нужно убирать, название, цена, атрибуты, сумма - пусть будут.

**Comment by zakhnikita** [comment]
Как еще изменить?
 ![2015-04-19 16 07 39](https://cloud.githubusercontent.com/assets/8578786/7219546/39d45dfa-e6ae-11e4-8ca6-1fb65fcf18dd.png)
