### ISSUE TITLE
Разделить промокоды и скидки

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/Benefito#2]
Промокоды - строки, ввод которых предоставляет скидку на заказ.
Скидки - временное уменьшение цены на товар или группу товаров, визуально отображаемое в каталоге и на странице товара.
Промокоды могут применяться поверх скидочных товаров.

**Comment by zakhnikita** [comment]
Сделано
![2015-04-06 0 00 14](https://cloud.githubusercontent.com/assets/8578786/6998592/02c4f54a-dbf0-11e4-9f46-b60e0b7b0b91.png)
![2015-04-06 0 00 22](https://cloud.githubusercontent.com/assets/8578786/6998593/02e15730-dbf0-11e4-9a05-38da84727622.png)
